apiVersion: v1
kind: Pod
metadata:
  name: wiz-demo-pod
  labels:
    env: test
spec:
  containers:
  - name: wiz-demo-pod
    image: centos:7
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "3650d"]
    securityContext:
      privileged: true
